### ISSUE TITLE
PURL resolves to html

### ISSUE THREAD

**Issue by dosumis** [hkir-dev/developing_human_brain_atlas_ontology#1]
https://brain-bican.github.io/developing_human_brain_atlas_ontology/ -->

html file 
```html
<!DOCTYPE html>
<html
  lang="en"
  
  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
  data-a11y-animated-images="system" data-a11y-link-underlines="true"
  >




  <head>
    <meta charset="utf-8">

```

- which seems to be BICAN PURL repo

<img width="494" alt="image" src="https://github.com/brain-bican/developing_human_brain_atlas_ontology/assets/112839/a9d00674-0fcc-489f-9f0e-af7debe8b5a2">

**Comment by hkir-dev** [comment]
Which PURL did you tried? The link you provided looks like a GitHub.io page.

Working PURLs are:

- https://purl.brain-bican.org/ontology/dhbao/dhbao.owl
- https://purl.brain-bican.org/ontology/dhbao/dhbao-base.owl
- https://purl.brain-bican.org/ontology/dhbao/latest/dhbao.owl

**Comment by hkir-dev** [comment]
Updated the PURL link at homepage
